
# GetAll
# Consultar os produtos cadastrados
GET http://localhost:3000/product

###  
# Get by Id
# Consultar os produtos por Id
GET http://localhost:3000/product/3

###  
# Update a product by Id
# Atualizar um produto utilizando a Id
PUT http://localhost:3000/product/3
Content-Type: application/json

    {
        "product_name":"Headset Gamer",
        "product_desc":"Headset Gamer Prolix Tool 2",
        "quantity":17,
        "price":89.9
    }
  
###
# Create a produtc
# Criar um produto
POST http://localhost:3000/product/
Content-Type: application/json

    {
        "product_name":"Notebook Dell ",
        "product_desc":"Notebook Dell Inspiron 3184",
        "quantity":10,
        "price":2599
    }
  
###
# Delete a produtc by Id
# Deletar um produto usando a Id
DELETE http://localhost:3000/product/2
